[workspace]
members = [
    "opentelemetry",
    "opentelemetry-*",
    "opentelemetry-*/examples/*",
    "opentelemetry-otlp/tests/*",
    "examples/*",
    "stress",
]
# Any deleted crates with remaining README
exclude = []
resolver = "2"

[profile.bench]
# https://doc.rust-lang.org/cargo/reference/profiles.html#bench
# See function names in profiling reports.
# 2/true is too much, 0 is not enough, 1 is just right for back traces
debug = 1

[workspace.dependencies]
async-std = "1.10"
async-trait = "0.1"
bytes = "1"
env_logger = { version = "0.10", default-features = false } # env_logger requires a newer MSRV
futures-core = "0.3"
futures-executor = "0.3"
futures-util = { version = "0.3", default-features = false }
hyper = { version = "1.3", default-features = false }
hyper-util = "0.1"
http = { version = "1.1", default-features = false, features = ["std"] }
http-body-util = "0.1"
log = "0.4.21"
once_cell = "1.13"
ordered-float = "4.0"
pin-project-lite = "0.2"
prost = "0.12"
prost-build = "0.12"
prost-types = "0.12"
rand = { version = "0.8", default-features = false }
reqwest = { version = "0.12", default-features = false }
serde = { version = "1.0", default-features = false }
serde_json = "1.0"
temp-env = "0.3.6"
thiserror = { version = "1", default-features = false }
tonic = { version = "0.11", default-features = false }
tonic-build = "0.11"
tokio = { version = "1", default-features = false }
tokio-stream = "0.1.1"
tracing = { version = "0.1", default-features = false }
tracing-core = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", default-features = false }
url = { version = "2.2", default-features = false }

[patch.crates-io]
tonic = { git = "https://github.com/hyperium/tonic.git", rev = "3c013ea89558e8e2bb4b2af3949c342188ebd485" }
